version: '3'

services:
  nats:
    image: nats:latest
    entrypoint: "/gnatsd -DV"
    expose:
      - 4222
    ports:
      - 8222:8222
    hostname: nats-server
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
  api-service:
    image: api-container
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - 8080:80
  map-matcher:
    image: map-matcher-container
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
    links:
      - consul