version: '3'

services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - 8500:8500
      - 8600:8600
  api-service:
    image: api-container
    ports:
      - "3000:3000"
      - "8081:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - p=4567
    links:
      - consul
  # microweb:
  #   image: microhq/micro
  #   command: web --address=0.0.0.0:8080
  #   ports:
  #     - "90:8080"
  #   environment:
  #     - MICRO_REGISTRY=consul
  #     - MICRO_REGISTRY_ADDRESS=consul
  #     - MICRO_API_NAMESPACE=microsweb
  #   links:
  #     - consul
  #     - api-service