version: "3"

services:
  # nats:
  #   image: nats:latest
  #   entrypoint: "/gnatsd -DV"
  #   expose:
  #     - 4222
  #   ports:
  #     - 8222:8222
  #   hostname: nats-server
  # consul:
  #   image: consul:latest
  #   command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
  #   hostname: consul
  #   ports:
  #     - 8300:8300
  #     - 8500:8500
  #     - 8600:8600
  # api:
  #   build: ./api
  #   environment:
  #     - NATS_URI=nats://nats:4222
  #   depends_on:
  #     - nats
  #   ports:
  #     - 8080:80
  # osrm-server:
  #   image: patreu22/ioslab-osrm-image:latest
  #   ports:
  #     - 5000:5000
  #   command: sh -c "osrm-routed --algorithm mld berlin-latest.osrm"
  map-matcher:
    build: ./map-matcher
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - NATS_URI=nats://nats:4222
      - OSRM_URI=osrm-server:5000
    depends_on:
      - nats
    links:
      - consul
      - nats
  pollution-matcher:
    build: ./pollution-matcher
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - NATS_URI=nats://nats:4222
    depends_on:
      - nats
    links:
      - consul
      - nats
  price-calculator:
    build: ./toll-calculator
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - NATS_URI=nats://nats:4222
    depends_on:
      - nats
    links:
      - consul
      - nats
